features.txt <- read.csv('./UCI HAR Dataset/features.txt', header = FALSE, sep = '')
features.txttome <- as.character(features[,2])
X.Train.data <- read.table('./UCI HAR Dataset/train/X_train.txt')
activity.train <- read.csv('./UCI HAR Dataset/train/Y_train.txt', header = FALSE, sep = '')
subject.train <- read.csv('./UCI HAR Dataset/train/subject_train.txt',header = FALSE,sep = '')
data.train <- data.frame(subject.train,activity.train,X.Train.data)
names(data.train) <- c(c('subject.train','activity.train'),features.txttome)
datatest.x <- read.table('./UCI HAR Dataset/test/X_test.txt')
activity.test <- read.csv('./UCI HAR Dataset/test/y_test.txt', header = FALSE, sep = ' ')
subject.test <- read.csv('./UCI HAR Dataset/test/subject_test.txt', header = FALSE, sep = ' ')
data.testA <-  data.frame(subject.test, activity.test, datatest.x)
names(data.testA) <- c(c('subject.train', 'activity.train'), features.txttome)
datafor.all <- rbind(data.train,data.testA)
mean_std.select <- grep('mean|std', features.txttome)
data.sub <- datafor.all[,c(1,2,mean_std.select + 2)] 
activity.read.labels <- read.table('./UCI HAR Dataset/activity_labels.txt', header = FALSE)
activity.read.labels <- as.character(activity.read.labels[.2])
data.sub$activity <- activity.read.labels[data.sub$activity]
names(data.sub) <- new.name
name.new <- names(data.sub)
name.new <- gsub("[(][)]", "", name.new)
name.new <- gsub("^t", "TimeDomain_", name.new)
name.new <- gsub("^f", "FrequencyDomain_", name.new)
name.new <- gsub("Acc", "Accelerometer", name.new)
name.new <- gsub("Gyro", "Gyroscope", name.new)
name.new <- gsub("Mag", "Magnitude", name.new)
name.new <- gsub("-mean-", "_Mean_", name.new)
name.new <- gsub("-std-", "_StandardDeviation_", name.new)
name.new <- gsub("-", "_", name.new)
names(data.sub) <- name.new
data.tidy <- aggregate(data.sub[,3:81], by = list(activity = data.sub$activity, subject = data.sub$subject),FUN = mean)
write.table(x = data.tidyset, file = "data_tidy.txt", row.names = FALSE)
